### ISSUE TITLE
Install issue

### ISSUE THREAD

**Issue by kevkha** [rainabba/nwk-socket.io#1]
I appears there is an type on 'node injex.js' in your installation section where it should be 'node index.js'.

I attempted to run your code but getting this error

<pre>
C:\nwk-socket.io>node index.js
module.js:338
    throw err;
          ^
Error: Cannot find module 'hapi'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (C:\nwk-socket.io\index.js:5:12)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)

C:\nwk-socket.io>
</pre>

**Comment by rainabba** [comment]
Not sure what you mean about "injex", but that error is telling you that a module isn't found. In this case, Hapi.

Did you run "npm install"?

**Comment by kevkha** [comment]
You have a typo here

![image](https://cloud.githubusercontent.com/assets/1807308/7080669/79788392-defb-11e4-86ba-c4e9a96e87bb.png)

I see. I thought your script will take care of that. Perhaps, you can document that for newbie like me :) I will give it shot again. Thanks.

**Comment by rainabba** [comment]
I see. I'll square away the typo and add see about scripting the npm install command, but if you're going to be doing anything with node.js, just assume it's a requirement EVERY single time you pull a project because most people don't script it and it's required to manage dependencies for package.json.

Also, you're welcome to submit a pull request for the typo and such issues with a repo. That's the heart of contributing to open-source; "contributing" where you feel comfortable doing so.

I'm learning myself so I appreciate the feedback. It's helps me better understand the sort of issues i need to look out for as I share projects.

**Comment by rainabba** [comment]
Merged

**Comment by kevkha** [comment]
Ok. I submitted a pull request. It's my first so hopefully it went ok :)
I'm on Win7 and getting new error during 'npm install' so will install .NET Framework 2.0 SDK and try again. Thanks.

<pre>
\nwk-socket.io\node_modules\socket.io\node_modules\engine.io\node_modul
es\ws>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node
-gyp\bin\node-gyp.js" rebuild )  else (rebuild)
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
MSBUILD : error MSB3428: Could not load the Visual C++ component "VCBuild.exe". To fix this, 1) install the .NET Framework 2.0 SD
K, 2) install Microsoft Visual Studio 2005 or 3) add the location of the component to the system path if it is installed elsewher
e.  [\nwk-socket.io\node_modules\socket.io\node_modules\engine.io\node
_modules\ws\build\binding.sln]
MSBUILD : error MSB3428: Could not load the Visual C++ component "VCBuild.exe". To fix this, 1) install the .NET Framework 2.0 SD
K, 2) install Microsoft Visual Studio 2005 or 3) add the location of the component to the system path if it is installed elsewher
e.  [\socket.io\node_modules\engine.io\node
_modules\ws\build\binding.sln]
</pre>

**Comment by kevkha** [comment]
Success!

<pre>
C:\nwk-socket.io>node index.js
app v1.0.0 running at: http://GIZMO:8883
nwkServer:sockns:connection
nwkServer:sockns:emit:pong
sockns.on:ping { data: { from: 'deskSock:connect' } }
player disconnected
nwkServer:sockns:connection
nwkServer:sockns:emit:pong
sockns.on:ping { data: { from: 'deskSock:connect' } }
</pre>

**Comment by rainabba** [comment]
Congrats. node-gyp can be difficult. Enjoy!

**Comment by kevkha** [comment]
I'm still blurry with the concepts though. I want to learn how socket.io can be run with NWK and see if it can be used to control Webchimera Player/plugin inside NWK like this project using socket.io and OMXControl to control OMXPlayer, http://blog.donaldderek.com/2013/06/build-your-own-google-tv-using-raspberrypi-nodejs-and-socket-io/
